/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 rocket.glb
Author: paburoviii (https://sketchfab.com/paburoviii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/models/2f04130e3c78439d9765b5ac71b333d2
Title: Space Shuttle Atlantis
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rocket.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 5.66, 6.87]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Rocket_Details_01_Rocket_Details_Material_0.geometry} material={materials.Rocket_Details_Material} />
          <mesh geometry={nodes.Rocket_Details_01_Rocket_Material_0.geometry} material={materials.Rocket_Material} />
          <mesh geometry={nodes.Rocket_01_White_Metal_0.geometry} material={materials.White_Metal} />
          <mesh geometry={nodes.Rocket_01_Rocket_Material_0.geometry} material={materials.Rocket_Material} />
          <mesh geometry={nodes.Rocket_Details_01_Rocket_Details_Material_0_1.geometry} material={materials.Rocket_Details_Material} />
          <mesh geometry={nodes.Rocket_Details_01_Rocket_Material_0_1.geometry} material={materials.Rocket_Material} />
          <mesh geometry={nodes.Rocket_01_White_Metal_0_1.geometry} material={materials.White_Metal} />
          <mesh geometry={nodes.Rocket_01_Rocket_Material_0_1.geometry} material={materials.Rocket_Material} />
          <mesh geometry={nodes.Turbine_Group1_Turbine_Material_0.geometry} material={materials.Turbine_Material} />
          <mesh geometry={nodes.Turbine_Group1_Rubber_0.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.Turbine_Group1_White_Metal_0.geometry} material={materials.White_Metal} />
          <mesh geometry={nodes.Plane_01_Grey_metal_0.geometry} material={materials.Grey_metal} />
          <mesh geometry={nodes.Plane_01_White_Metal_0.geometry} material={materials.White_Metal} />
          <mesh geometry={nodes.Plane_01_Orange_light_metal_0.geometry} material={materials.Orange_light_metal} />
          <mesh geometry={nodes.Plane_01_Chrome_0.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.Plane_01_Black_metal1_0.geometry} material={materials.Black_metal1} />
          <mesh geometry={nodes.Plane_01_Plane_01_Material_0.geometry} material={materials.Plane_01_Material} />
          <mesh geometry={nodes.Orange_Parts_Orange_Material_0.geometry} material={materials.Orange_Material} />
          <mesh geometry={nodes.Black_Parts_Black_Material_0.geometry} material={materials.Black_Material} />
          <mesh geometry={nodes.TubesGroup1_Tubes_Material_0.geometry} material={materials.Tubes_Material} />
          <mesh geometry={nodes.Plane_02Group1_Plane02_Material_0.geometry} material={materials.Plane02_Material} />
          <mesh geometry={nodes.WingGroup1_Wing_Material_0.geometry} material={materials.Wing_Material} />
          <mesh geometry={nodes.Wing_02Group1_Wing_02_Material_0.geometry} material={materials.Wing_02_Material} />
          <mesh geometry={nodes.Back1_Back_Material_0.geometry} material={materials.Back_Material} />
          <mesh geometry={nodes.Ceiling1_Ceiling_Material_0.geometry} material={materials.Ceiling_Material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rocket.glb')
